### ISSUE TITLE
Task 3

### ISSUE THREAD

**Issue by slawiko** [DimaGavrushko/GavrushkoUP#2]
@DimaGavrushko 

CSS:
- не совсем правильное использование id. Вообще это уникальный идентификатор. Его используют, например, в случае динамического списка, когда каждый элемент списка с какой-то уникальной предварительно сгенерированной id. В вашем случае правильно будет заменить все на классы.
- названия классов принято писать маленькими буквами, через дефисы.
- отрицательные `margin`, `padding`, `top` ... - плохая практика. Обычно, если начинают их использовать, это свидетельствует о неправильной верстке.

**Comment by DimaGavrushko** [comment]
мне просто заметить id на классы и убрать отрицательные значения?

**Comment by DimaGavrushko** [comment]
визуально все правильно сделано?(старался его сделать responsive)

**Comment by slawiko** [comment]
К сожалению responsive не заметил, поэтому и отметка не такая высокая. Вы не совсем правильно поняли, видимо. Почитайте про media-запросы в CSS [тут](https://developer.mozilla.org/en-US/docs/Web/CSS/@media) и [тут](http://htmlbook.ru/css/value/media) например.

**Comment by DimaGavrushko** [comment]
http://rightblog.ru/324 вот примеры responsive дизайна 
Мой сайт примерно так же делает при уменьшении размеров

**Comment by DimaGavrushko** [comment]
https://pp.userapi.com/c824604/v824604009/cf1da/jIAZY7Qz2BE.jpg

**Comment by DimaGavrushko** [comment]
я именно такого результата специально и добивался

**Comment by DimaGavrushko** [comment]
https://pp.userapi.com/c840332/v840332009/5bba8/1WizBIxkizY.jpg
Вот на мобильной версии у меня все так же сужается относительно всех размеров экрана

**Comment by slawiko** [comment]
С постами вопросов больше нет, выглядит хорошо. Но хэдер немного смущает:
<img width="423" alt="2018-02-27 21 44 33" src="https://user-images.githubusercontent.com/10272192/36747928-6cecfdfa-1c07-11e8-81c8-29afd0da6d50.png">
Так задумано? Если да, то неудобно и надо поправить. Если нет, то надо поправить.

**Comment by DimaGavrushko** [comment]
Хорошо,попытаюсь исправить

**Comment by DimaGavrushko** [comment]
Хорошо,попытаюсь исправить

**Comment by slawiko** [comment]
Отмучили. Но зачем так торопились и не следили за отступами, некрасиво же.

В следующий раз отпишите по готовности тут, а не создавайте тэг.
