### ISSUE TITLE
Task 4

### ISSUE THREAD

**Issue by batist73** [DimaGavrushko/GavrushkoUP#3]
@DimaGavrushko 

**getPhotoPosts:**
* ``filterConfig.createdAt == 'Invalid Date'`` - странная проверка :) Следует использовать instanceof Date.

**editPhotoPost:**
* При валидации объекта post вы запрещаете ему иметь неизменяемые поля. Хотя, возможно, лучше просто игнорировать их?

**Comment by DimaGavrushko** [comment]
не очень понял второе замечание,можете пояснить?


2018-03-14 23:45 GMT+03:00 Anton Grigoriev <notifications@github.com>:

**Comment by batist73** [comment]
@DimaGavrushko 

Конечно. Например, вызов ``editPhotoPost('4', { description: 'new', id: '5' })`` вернёт false, хотя description вполне может быть обновлён, несмотря на переданный id.

**Comment by DimaGavrushko** [comment]
т.е. discription должен все равно обновиться не смотря на то,что передан неправильный параметр?

**Comment by batist73** [comment]
@DimaGavrushko 

Это просто один из вариантов. В общем и целом на ваше усмотрение.
