### ISSUE TITLE
Task 7

### ISSUE THREAD

**Issue by batist73** [DimaGavrushko/GavrushkoUP#4]
@DimaGavrushko 

**node_modules:**
* Эту директорию обязательно надо добавлять в .gitignore, так как все модули из dependencies вашего приложения всегда можно установить с помощью команды npm install.

**Задание:**
* В задании подразумевалось, что на 10 баллов необходимо реализовать отдачу статики как с помощью Express, так и средствами одного http модуля, то есть попробовать и то и то. Поэтому добавьте обработку статики на Express (благо, это не долго), внеся Express в dependencies вашего проекта и воспользовавшись стандартным мидлваром express.static. Можете поместить уже написанный с помощью http сервер в файл app-http.js, а в app.js реализовать сервер с Express, так как в дальнейшем вы будете работать именно с ним. Баллы за эту доработку снижать не будем. Просто для полноты картины стоит добавить Express статику.

**Сервер:**
* Вы разместили сервер в директории task7, что не совсем удобно, так как приходится стартовать сервер (командой node) из этой директории, а не из корня приложения. Вообще, обычно принято иметь точку входа именно в корне приложения (можете считать, что всё ваше приложение и является сервером, просто в том числе отдаёт клиент). package.json также следует располагать в корне приложения. То есть, всё содержимое папки task7 можно разместить в корне.

**Пути:**
* Сейчас, чтобы получить клиент, необходимо обратиться по адресу localhost:3000/public/index.html, что не совсем удобно. Обычно клиент получают из корня сервера, то есть по адресу localhost:3000 в вашем случае.

**Comment by DimaGavrushko** [comment]
доработал

**Comment by batist73** [comment]
@DimaGavrushko 

Директорию public видимо тоже стоит вынести в корень. Либо подправить путь к статике.

**Comment by DimaGavrushko** [comment]
![default](https://user-images.githubusercontent.com/22750804/38177717-3478dee6-360e-11e8-8ebd-33da7dca0be8.PNG)
простите,забыл вчера докомитить :)
я уже новый тег не создавал,просто залил на репозиторий

**Comment by batist73** [comment]
@DimaGavrushko 

👍
